### ISSUE TITLE
Text that doesn't match an enum value defaults to 0

### ISSUE THREAD

**Issue by petekledaras** [shoma07/ransack-enum#2]
I have an enum like this:

` enum status: {
    visit: 0,
    signing_up: 1,
    signed_in: 2
    failed_login: 3
  }`

When I do a search on something like 'liyfsljyfew', the query that's generated contains

` ... ("session_statuses"."status" = 0) ...`

So it appears that a search query that does not match any of the enum key values defaults to 0.  But 0 means 'visit', so I am getting a ton of extraneous search hits.

Is there any way to default a mismatch to something like 999, or omit the sql condition if the search text does not match an enum key?

**Comment by petekledaras** [comment]
Well, I just created a ransacker that handles this.  Easy enough.

**Comment by benoror** [comment]
@petekledaras mind sharing the `ransacker` for searching enums with strings?

**Comment by benoror** [comment]
Ended up using something very simple:

```ruby
ransacker :status, formatter: proc { |key| STATUSES[key.to_sym] }
```
